import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type SchemaObject = {
  $ref?: string;
  type?: string | string[];
  enum?: string[];
  required?: string[];
  properties?: Record<string, SchemaObject>;
  items?: SchemaObject;
  additionalProperties?: boolean | SchemaObject;
};

type OpenApiDocument = {
  info: {
    title: string;
    version: string;
  };
  paths: Record<
    string,
    Record<
      string,
      {
        operationId: string;
        requestBody?: {
          content?: {
            'application/json'?: {
              schema: SchemaObject;
            };
          };
        };
        responses: Record<
          string,
          {
            content?: {
              'application/json'?: {
                schema: SchemaObject;
              };
            };
          }
        >;
      }
    >
  >;
  components: {
    schemas: Record<string, SchemaObject>;
  };
};

type Operation = {
  method: string;
  path: string;
  operationId: string;
  pathParams: string[];
  requestType?: string;
  responseType: string;
};

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../../..');
const openApiPath = resolve(repoRoot, 'apps/idl/src/openapi/openapi.json');

const generatedBanner = `// This file is generated by apps/idl/scripts/generate-openapi.ts.\n// Do not edit it manually.\n\n`;

function pascalCase(value: string) {
  return value
    .replace(/(^|[-_ ./])([a-zA-Z0-9])/g, (_, __, char: string) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

function refName(ref: string) {
  const prefix = '#/components/schemas/';

  if (!ref.startsWith(prefix)) {
    throw new Error(`Unsupported ref: ${ref}`);
  }

  return ref.slice(prefix.length);
}

function schemaToType(schema: SchemaObject, required = true): string {
  if (schema.$ref) {
    return refName(schema.$ref);
  }

  if (schema.enum) {
    return schema.enum.map((item) => JSON.stringify(item)).join(' | ');
  }

  if (Array.isArray(schema.type)) {
    return schema.type.map((type) => schemaToType({ ...schema, type }, required)).join(' | ');
  }

  switch (schema.type) {
    case 'array':
      return `${schema.items ? schemaToType(schema.items) : 'unknown'}[]`;
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'object':
      return objectSchemaToType(schema);
    case 'string':
      return 'string';
    case undefined:
      if (schema.additionalProperties === true) {
        return 'Record<string, unknown>';
      }

      return required ? 'unknown' : 'unknown | undefined';
    default:
      throw new Error(`Unsupported schema type: ${String(schema.type)}`);
  }
}

function objectSchemaToType(schema: SchemaObject) {
  if (!schema.properties) {
    if (schema.additionalProperties === true) {
      return 'Record<string, unknown>';
    }

    if (typeof schema.additionalProperties === 'object') {
      return `Record<string, ${schemaToType(schema.additionalProperties)}>`;
    }

    return 'Record<string, unknown>';
  }

  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties).map(([name, property]) => {
    const optional = required.has(name) ? '' : '?';
    return `  ${JSON.stringify(name)}${optional}: ${schemaToType(property, required.has(name))};`;
  });

  if (schema.additionalProperties === true) {
    fields.push('  [key: string]: unknown;');
  }

  return `{\n${fields.join('\n')}\n}`;
}

function collectOperations(document: OpenApiDocument): Operation[] {
  const operations: Operation[] = [];

  for (const [path, methods] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      const successResponse = operation.responses['200'] ?? operation.responses['201'];
      const responseSchema = successResponse?.content?.['application/json']?.schema;

      if (!responseSchema) {
        throw new Error(`Missing JSON success response schema for ${method.toUpperCase()} ${path}`);
      }

      const requestSchema = operation.requestBody?.content?.['application/json']?.schema;

      operations.push({
        method,
        path,
        operationId: operation.operationId,
        pathParams: [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]),
        requestType: requestSchema ? schemaToType(requestSchema) : undefined,
        responseType: schemaToType(responseSchema),
      });
    }
  }

  return operations;
}

function generateTypes(document: OpenApiDocument, operations: Operation[]) {
  const schemas = Object.entries(document.components.schemas)
    .map(([name, schema]) => `export type ${name} = ${schemaToType(schema)};`)
    .join('\n\n');

  const operationTypes = operations
    .map((operation) => {
      const name = pascalCase(operation.operationId);
      const requestType = operation.requestType ?? 'undefined';

      return [
        `export type ${name}OperationRequest = ${requestType};`,
        `export type ${name}OperationResponse = ${operation.responseType};`,
      ].join('\n');
    })
    .join('\n\n');

  return `${generatedBanner}${schemas}\n\n${operationTypes}\n`;
}

function generateWebClient(operations: Operation[]) {
  const imports = operations
    .flatMap((operation) => {
      const name = pascalCase(operation.operationId);
      return operation.requestType ? [`${name}OperationRequest`, `${name}OperationResponse`] : [`${name}OperationResponse`];
    })
    .sort()
    .join(',\n  ');

  const methods = operations
    .map((operation) => {
      const name = pascalCase(operation.operationId);
      const requestType = `${name}OperationRequest`;
      const responseType = `${name}OperationResponse`;
      const hasBody = operation.requestType !== undefined;
      const pathArgs = operation.pathParams.map((param) => `${param}: string`);
      const args = [...pathArgs, ...(hasBody ? [`payload: ${requestType}`] : [])].join(', ');
      const path = operation.pathParams.reduce(
        (nextPath, param) => nextPath.replace(`{${param}}`, `\${${param}}`),
        operation.path,
      );
      const pathLiteral = operation.pathParams.length > 0 ? `\`${path}\`` : `'${operation.path}'`;
      const axiosCall =
        operation.method === 'get'
          ? `api.get<${responseType}>(${pathLiteral})`
          : hasBody
            ? `api.${operation.method}<${responseType}>(${pathLiteral}, payload)`
            : `api.${operation.method}<${responseType}>(${pathLiteral})`;

      return `  async ${operation.operationId}(${args}) {\n    const response = await ${axiosCall};\n    return response.data;\n  },`;
    })
    .join('\n\n');

  return `${generatedBanner}import axios from 'axios';\n\nimport type {\n  ${imports},\n} from '@ai-mind-clone/shared/generated/openapi';\n\nexport const api = axios.create({\n  baseURL: import.meta.env.VITE_API_BASE_URL ?? '',\n});\n\nexport const agentApiClient = {\n${methods}\n};\n`;
}

function generateServerContract(operations: Operation[]) {
  const imports = operations
    .flatMap((operation) => {
      const name = pascalCase(operation.operationId);
      return [`${name}OperationRequest`, `${name}OperationResponse`];
    })
    .sort()
    .join(',\n  ');

  const routes = operations
    .map((operation) => {
      const name = pascalCase(operation.operationId);
      const requestType = `${name}OperationRequest`;
      const responseType = `${name}OperationResponse`;

      return `  ${operation.operationId}: {\n    method: '${operation.method.toUpperCase()}',\n    path: '${operation.path}',\n  } satisfies ApiRoute<${requestType}, ${responseType}>,`;
    })
    .join('\n');

  return `${generatedBanner}import type {\n  ${imports},\n} from '@ai-mind-clone/shared/generated/openapi';\n\nexport type ApiRoute<Request, Response> = {\n  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';\n  path: string;\n  request?: Request;\n  response?: Response;\n};\n\nexport const apiRoutes = {\n${routes}\n};\n`;
}

async function writeGeneratedFile(path: string, content: string) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

async function main() {
  const document = JSON.parse(await readFile(openApiPath, 'utf8')) as OpenApiDocument;
  const operations = collectOperations(document);

  await Promise.all([
    writeGeneratedFile(resolve(repoRoot, 'packages/shared/src/generated/openapi.ts'), generateTypes(document, operations)),
    writeGeneratedFile(resolve(repoRoot, 'apps/web/src/generated/api-client.ts'), generateWebClient(operations)),
    writeGeneratedFile(resolve(repoRoot, 'apps/server/src/generated/api-contract.ts'), generateServerContract(operations)),
  ]);

  console.log(`Generated ${operations.length} operations from ${document.info.title} ${document.info.version}.`);
}

await main();
